service: serverless-plugin-environment-secret
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_OPTIONS: '--enable-source-maps'

functions:
  function1:
    events:
      - http:
          path: /
          method: GET
    handler: index.handler

custom:
  environment:
    NotSecret: 'not-a-secret'
    DefinitelyASecret:
      # You'll need to create a secret in your AWS account named ${stage}/some-secret-id
      SecretValue: ${ssm:/aws/reference/secretsmanager/${self:provider.stage}/some-secret-id}
    SLS_ENVIRONMENT_SECRET_NAME: ${self:provider.stage}/example-enivonment-secret

plugins:
  - ../../index.js
  - serverless-offline
